<a href="https://colab.research.google.com/github/rexona8/GB_Python_dz/blob/main/seminar9_dz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("sample_data/california_housing_train.csv")

In [17]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

task40 start

In [61]:
pop = df[df["population"] < 500]

In [54]:
pop

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0
...,...,...,...,...,...,...,...,...,...
16944,-124.14,40.67,23.0,580.0,117.0,320.0,109.0,4.2054,130600.0
16951,-124.15,40.81,50.0,340.0,74.0,235.0,83.0,1.7500,67500.0
16969,-124.17,40.80,52.0,661.0,316.0,392.0,244.0,0.9570,60000.0
16982,-124.18,40.62,35.0,952.0,178.0,480.0,179.0,3.0536,107000.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0

In [58]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [60]:
pop["population"].mean()

307.9056839475328

task40 end

task42 start

In [75]:
hous_min_pop = df[df['population'] == df['population'].min()]['households'].max()

In [76]:
hous_min_pop

4.0

task42 end